#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "zoraxy"
name = "Zoraxy"
description.en = "General purpose HTTP reverse proxy and forwarding tool"
description.fr = "Outil de proxy inverse et de transfert HTTP à usage général"

version = "3.1.6~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
website = "https://zoraxy.arozos.com/index.html"
admindoc = "https://github.com/tobychui/zoraxy/wiki/Getting-Started"
code = "https://github.com/tobychui/zoraxy"

[integration]
yunohost = ">= 11.2.30"
architectures = ["i386", "amd64", "armhf", "arm64"]
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    extract = false
    rename = "zoraxy"
    amd64.url = "https://github.com/tobychui/zoraxy/releases/download/v3.1.6/zoraxy_linux_amd64"
    amd64.sha256 = "2213a61cc3344f03e37fb161132a84da6cc60c1ac9b9054e143b544c7342b3bd"
    i386.url = "https://github.com/tobychui/zoraxy/releases/download/v3.1.6/zoraxy_linux_386"
    i386.sha256 = "37752545e2686510ac93e753711358bd435253e5449c63470f70cc073feccc4d"
    armhf.url = "https://github.com/tobychui/zoraxy/releases/download/v3.1.6/zoraxy_linux_arm"
    armhf.sha256 = "9f310edad6786925c925a9c1a1e330683f14700ac5d9eec4e693c72b818b513f"
    arm64.url = "https://github.com/tobychui/zoraxy/releases/download/v3.1.6/zoraxy_linux_arm64"
    arm64.sha256 = "065961f709db3c213018c7105d8d81310a654ebd4d26dedee675116d92dddbdf"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.i386 = "^zoraxy_linux_386$"
    autoupdate.asset.amd64 = "^zoraxy_linux_amd64$"
    autoupdate.asset.armhf = "^zoraxy_linux_arm$"
    autoupdate.asset.arm64 = "^zoraxy_linux_arm64$"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
